parameters:
- name: sign
  type: boolean
  default: false
- name: kernel
  type: string
  default: 'kernel5_4'

jobs:
- job: distribution_${{ parameters.kernel }} # drop_package_linux_${{ jobname }}
  displayName: Distribution
  pool:
    type: linux
  variables:
    ob_outputDirectory: $(Build.SourcesDirectory)/artifacts/dist
    # ob_artifactSuffix: _$(kernel) # drop_package_linux_${{ jobname }}
  steps:
  - task: PowerShell@2
    displayName: Prepare Build Machine
    inputs:
      pwsh: true
      filePath: scripts/prepare-machine.ps1
      arguments: -ForContainerBuild
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_linux_$(kernel)_Debug
      path: $(Build.SourcesDirectory)/artifacts/bin/linux
      pattern: '*.tar'
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_linux_$(kernel)_Release
      path: $(Build.SourcesDirectory)/artifacts/bin/linux
      pattern: '*.tar'
  - script: | # rebuild artifacts with correct permissions and symlink attributes.
      cd $(Build.SourcesDirectory)/artifacts/bin/linux
      rm -rf */
      find -name "*.tar" -exec tar -xvf '{}' \;
  - task: PowerShell@2
    displayName: Distribution
    inputs:
      pwsh: false
      filePath: scripts/package-distribution.ps1
      ${{ if eq(parameters.kernel, 'kernel6_8') }}:
        arguments: -Time64Distro
  - script: | # prepare 2 sets of packages for signing with different keys (gen = general purpose, cbl = cbl-mariner)
      mkdir $(Build.SourcesDirectory)/artifacts/dist/gen
      find $(Build.SourcesDirectory)/artifacts/dist -type f -exec mv -t $(Build.SourcesDirectory)/artifacts/dist/gen/ {} +
      cp -r $(Build.SourcesDirectory)/artifacts/dist/gen/ $(Build.SourcesDirectory)/artifacts/dist/cbl/
  - ${{ if not(eq(parameters.sign, false)) }}:
    - task: onebranch.pipeline.signing@1
      displayName: Sign General Purpose Packages
      inputs:
        command: 'sign'
        signing_profile: 'CP-450779-pgpdetached'
        files_to_sign: '**/*.rpm;**/*.deb'
        search_root: $(Build.SourcesDirectory)/artifacts/dist/gen
  - ${{ if not(eq(parameters.sign, false)) }}:
    - task: onebranch.pipeline.signing@1
      displayName: Sign CBL Packages
      inputs:
        command: 'sign'
        signing_profile: 'CP-459159-pgpdetached'
        files_to_sign: '**/*.rpm;**/*.deb'
        search_root: $(Build.SourcesDirectory)/artifacts/dist/cbl
